#!/usr/bin/env python3
"""Canonical Latin naming layer — EgD-LATIN-001.

SAP field names are abbreviations of German words. That is a source-language accident, not
a design. This module derives a language-neutral canonical name for every field in the model
from the concept lexicon, and emits the register the site and the blueprint both read.

The legacy SAP name is never replaced in the data — it is the mirror's join key. It is
carried alongside the canonical name and surfaced on hover in the published surface.

Run from the repository root:  python3 scripts/latinize.py
"""
import glob
import json
import os
import re

import yaml

LEXICON = "schema/lexicon/latin-lexicon.yaml"
REGISTER = "schema/lexicon/CANONICAL-FIELDS.yaml"
SITE_JSON = "docs/model/lexicon.json"
BASE = "schema/sap-modules"

_STOP = re.compile(r"[^a-z0-9 ]+")


def load_lexicon():
    doc = yaml.safe_load(open(LEXICON))
    concepts = doc["concepts"]
    # longest phrase first so "cost center" beats "cost" and "center"
    concepts.sort(key=lambda c: -len(c["en"]))
    return doc, concepts


def canonical(description, concepts, legacy, taken):
    """Compose up to three concept abbreviations in order of appearance."""
    text = " " + _STOP.sub(" ", (description or "").lower()) + " "
    hits = []
    for c in concepts:
        needle = " " + c["en"] + " "
        pos = text.find(needle)
        if pos >= 0:
            hits.append((pos, c))
            text = text[:pos] + " " * len(needle) + text[pos + len(needle):]
    if not hits:
        return legacy, [], False
    hits.sort(key=lambda h: h[0])
    picked, seen_ab = [], set()
    for _, c in hits:
        if c["ab"] in seen_ab:  # a concept repeated in one description adds nothing
            continue
        seen_ab.add(c["ab"])
        picked.append(c)
        if len(picked) == 3:
            break
    name = "_".join(c["ab"] for c in picked)
    stem, n = name, 2
    while name in taken:
        name = f"{stem}{n}"
        n += 1
    taken.add(name)
    return name, picked, True


def build():
    doc, concepts = load_lexicon()
    register, stats = {}, {"fields": 0, "derived": 0, "underived": 0}
    used_concepts = set()

    for path in sorted(glob.glob(f"{BASE}/*/tables/*.yaml")):
        table = yaml.safe_load(open(path))
        if not isinstance(table, dict) or not table.get("table"):
            continue
        taken, mapping = set(), {}
        for field in table.get("fields") or []:
            legacy = str(field.get("name", ""))
            name, picked, derived = canonical(
                field.get("description", ""), concepts, legacy, taken)
            stats["fields"] += 1
            stats["derived" if derived else "underived"] += 1
            for c in picked:
                used_concepts.add(c["en"])
            mapping[legacy] = {
                "canonical": name,
                "latin": " ".join(c["la"] for c in picked) or None,
                "concepts": [c["en"] for c in picked],
                "derived": derived,
            }
        register[table["table"]] = {"module": table.get("module", ""), "fields": mapping}

    os.makedirs(os.path.dirname(REGISTER), exist_ok=True)
    with open(REGISTER, "w") as f:
        f.write("# Canonical field register — generated by scripts/latinize.py. Do not hand-edit.\n")
        f.write("# Legacy SAP names are the keys: the mirror joins on them and never discards them.\n")
        f.write("# © 2026 Dany Thériault / EVE Glyph Design. Pour le bien-être du peuple.\n")
        yaml.safe_dump(register, f, sort_keys=True, allow_unicode=True, width=100)

    os.makedirs(os.path.dirname(SITE_JSON), exist_ok=True)
    json.dump(
        {"lexicon_id": doc["lexicon_id"],
         "concepts": {c["en"]: {"la": c["la"], "ab": c["ab"]} for c in concepts},
         "register": register},
        open(SITE_JSON, "w"), ensure_ascii=False, separators=(",", ":"))

    pct = round(100 * stats["derived"] / max(stats["fields"], 1))
    print(f"{stats['fields']} fields · {stats['derived']} derived ({pct}%) · "
          f"{stats['underived']} keep legacy name · "
          f"{len(used_concepts)}/{len(concepts)} concepts in use")
    return stats


if __name__ == "__main__":
    build()
